### PR TITLE
feat: all purpose error screen

### PR DESCRIPTION
**Pull request by AdityaHarvi**
#### Summary of changes/features added:
- Added an all purpose error screen.

#### Screenshots of UI changes (update with each new commit): 
image

## Pull Request Checklist
- [ ] Unit test written?
- [ ] (**For later in project**) Integration tests written?
- [x] Java docs written?

### CODE REVIEW

**Comment by AdityaHarvi** [comment]
Might want to test this out on your phones super quick to make sure the images don't look wack on different screen sizes.
Best way to get to this screen is by commenting out L89 in MyBooksListFragment.java

**Review by ducklin5 — APPROVED** [review]
The code changes/additions look good. 
This is what the screen looks like on a smaller device though, not all of the image is shown:
image
I don't think it's a problem right now, so long as the error message shows up.

**Comment by AdityaHarvi** [comment]
lol yeah it doesn't look that bad but we can completely remove the images if needed and just have a blank screen

**Review by shadowciaw — COMMENTED** [review]
so how are you using error fragment now?

**Comment by AdityaHarvi** [comment]
> so how are you using error fragment now?
So far its used when we need an error check for the intent fails but it can be used for any sort of error check in the app

**Review by shadowciaw — APPROVED** [review]

**Pull request merged**
