### PR TITLE
feat: add requests-for-book activity

### PR DESCRIPTION
**Pull request by AdityaHarvi**
#### Summary of changes/features added:
- Added the `Requests for book` activity
- Users can view who is requesting their book and accept/reject them.

#### Screenshots of UI changes (update with each new commit): 
- Non modified screen.
image

- Rejecting the first person.
image

#### Link to referenced github issue: 
https://github.com/CMPUT301F20T05/CriEngine/issues/51

## Pull Request Checklist
- [ ] Unit test written?
- [ ] (**For later in project**) Integration tests written?
- [x] Java docs written?

### CODE REVIEW

**Comment by ducklin5** [comment]
JavaDoc looks good. LGTM 🚀

**Comment by ducklin5** [comment]
Oh noooo,   :\ merge deleted the comments -.-

**Review by ducklin5 — APPROVED** [review]
Okay those commits fixed. @AdityaHarvi  remember to pull, if you are still working on this. 
Otherwise, I think its ready for merge!
🚀

**Comment by AdityaHarvi** [comment]
Okay yeah I think this is where my commit messed up last night. I think the changes were pushed to master but they shouldn't impact anything else other than its own activity

**Comment by AdityaHarvi** [comment]
ty for the fix btw!

**Comment by AdityaHarvi** [comment]
@ducklin5 
@rjmah1 
these were the files to be reviewed:
https://github.com/CMPUT301F20T05/CriEngine/blob/master/client/app/src/main/java/com/example/criengine/Activities/RequestsForBookActivity.java
https://github.com/CMPUT301F20T05/CriEngine/blob/master/client/app/src/main/java/com/example/criengine/Adapters/NotificationAdapter.java
https://github.com/CMPUT301F20T05/CriEngine/blob/master/client/app/src/main/java/com/example/criengine/Objects/Notification.java

**Comment by AdityaHarvi** [comment]
Something i would need to change is to not automatically return to the previous screen because that seems to mess up the `back` button.

**Comment by rjmah1** [comment]
you can write a custom back button, just point it to the activity you want to go to when you back

**Review by rjmah1 — APPROVED** [review]
lgtm

**Pull request merged**
